export const getData = () => {
  return [
   {
    "id": "01-67867",
    "nombre": "CR Limon",
    "hato": "839-2",
    "raza": "Brahman Gris Puro",
    "fecha_nacimiento": "04/05/2022",
    "nombre_padre": "JDH Clanton de Manso",
    "cod_padre": "313-8",
    "nombre_madre": "CR Africa",
    "cod_madre": "858-4",
    "abuelo_paterno": "JDH Woodson De Manso 206/7",
    "abuelo_materno ": "JDH Karu Manso 800",
    "criador": "Ganaderia Colono Real S.A",
    "ultimo_propietario": "Ganaderia Colono Real S.A"
   },
   {
    "id": "01-69080",
    "nombre": "CR Garret",
    "hato": "865-2",
    "raza": "Brahman Gris Puro",
    "fecha_nacimiento": "09/10/2022",
    "nombre_padre": "MSP Garret Manso",
    "cod_padre": "348-1",
    "nombre_madre": "CR Normandia",
    "cod_madre": "957-5",
    "abuelo_paterno": "NMSU Garret Manso 7057",
    "abuelo_materno ": "JDH Wellington Manso 527-1",
    "criador": "Ganaderia Colono Real S.A",
    "ultimo_propietario": "Ganaderia Colono Real S.A"
   },
   {
    "id": "01-69084",
    "nombre": "CR Clanton II",
    "hato": "869-2",
    "raza": "Brahman Gris Puro",
    "fecha_nacimiento": "09/24/2022",
    "nombre_padre": "JDH Clanton de Manso",
    "cod_padre": "313-8",
    "nombre_madre": "CR Africa",
    "cod_madre": "858-4",
    "abuelo_paterno": "JDH Woodson De Manso 206/7",
    "abuelo_materno ": "JDH Karu Manso 800",
    "criador": "Ganaderia Colono Real S.A",
    "ultimo_propietario": "Ganaderia Colono Real S.A"
   },
   {
    "id": "01-69557",
    "nombre": "CR Karu",
    "hato": "875-2",
    "raza": "Brahman Gris Puro",
    "fecha_nacimiento": "11/05/2022",
    "nombre_padre": "JDH Karu Manso",
    "cod_padre": 800,
    "nombre_madre": "CR Meridian",
    "cod_madre": "250-0",
    "abuelo_paterno": "JDH Dakota Manso 599",
    "abuelo_materno ": "JDH MR Mosley Manso 368/1",
    "criador": "Ganaderia Colono Real S.A",
    "ultimo_propietario": "Ganaderia Colono Real S.A"
   },
   {
    "id": "01-69562",
    "nombre": "CR Vesubio",
    "hato": "880-2",
    "raza": "Brahman Gris Puro",
    "fecha_nacimiento": "11/16/2022",
    "nombre_padre": "JDH Karu Manso",
    "cod_padre": 800,
    "nombre_madre": "CR Pondur",
    "cod_madre": "284-0",
    "abuelo_paterno": "JDH Dakota Manso 599",
    "abuelo_materno ": "Mr Ah Rex Ponderosa 009",
    "criador": "Ganaderia Colono Real S.A",
    "ultimo_propietario": "Ganaderia Colono Real S.A"
   },
   {
    "id": "01-70020",
    "nombre": "CR Liberty",
    "hato": "887-3",
    "raza": "Brahman Gris Puro",
    "fecha_nacimiento": "01/06/2023",
    "nombre_padre": "JDH SIR Liberty Manso",
    "cod_padre": "847-5",
    "nombre_madre": "CR Lusitana",
    "cod_madre": "388-1",
    "abuelo_paterno": "JDH MR. Brahman Manso 175",
    "abuelo_materno ": "JDH Sir Marri Manso 557-4",
    "criador": "Ganaderia Colono Real S.A",
    "ultimo_propietario": "Ganaderia Colono Real S.A"
   },
   {
    "id": "01-70021",
    "nombre": "CR Limon",
    "hato": "888-3",
    "raza": "Brahman Gris Puro",
    "fecha_nacimiento": "08-01-2023",
    "nombre_padre": "MR H Maddoz Manso",
    "cod_padre": 684,
    "nombre_madre": "CR Londriana",
    "cod_madre": "330-8",
    "abuelo_paterno": "JDH MR Manso 360-1",
    "abuelo_materno ": "JDH Clanton De Manso 313-8",
    "criador": "Ganaderia Colono Real S.A",
    "ultimo_propietario": "Ganaderia Colono Real S.A"
   },
   {
    "id": "01-67868",
    "nombre": "CR Cobano",
    "hato": "840-2",
    "raza": "Brahman Gris Puro",
    "fecha_nacimiento": "04/13/2022",
    "nombre_padre": "CR Manaus",
    "cod_padre": "169-7",
    "nombre_madre": "CR Mandras",
    "cod_madre": "428-8",
    "abuelo_paterno": "JDH Sir LawfordK79YRPCCIR Manso 616-6",
    "abuelo_materno ": "JDH Beckton De Manso 490-7",
    "criador": "Ganaderia Colono Real S.A",
    "ultimo_propietario": "Ganaderia Colono Real S.A"
   },
   {
    "id": "01-68064",
    "nombre": "CR Iroquois",
    "hato": "844-2",
    "raza": "Brahman Gris Puro",
    "fecha_nacimiento": "05/20/2022",
    "nombre_padre": "JDh SIR Harper Manso",
    "cod_padre": "752-7",
    "nombre_madre": "CR Abigail",
    "cod_madre": "854-4",
    "abuelo_paterno": "JDH Sir Lawford Manso 616-6",
    "abuelo_materno ": "JDH Karu Manso 800",
    "criador": "Ganaderia Colono Real S.A",
    "ultimo_propietario": "Ganaderia Colono Real S.A"
   },
   {
    "id": "01-68438",
    "nombre": "CR Drover",
    "hato": "848-2",
    "raza": "Brahman Gris Puro",
    "fecha_nacimiento": "06/07/2022",
    "nombre_padre": "JDH Drover de Manso",
    "cod_padre": "962-2",
    "nombre_madre": "CR Llama del Bosque",
    "cod_madre": "798-3",
    "abuelo_paterno": "JDH Sir Liberty Manso 847/5",
    "abuelo_materno ": "Mr Ah Rex Ponderosa 009",
    "criador": "Ganaderia Colono Real S.A",
    "ultimo_propietario": "Ganaderia Colono Real S.A"
   },
   {
    "id": "01-68893",
    "nombre": "CR Hamburgo",
    "hato": "861-2",
    "raza": "Brahman Gris Puro",
    "fecha_nacimiento": "07-08-2022",
    "nombre_padre": "JDH Beckton de Manso",
    "cod_padre": "490-7",
    "nombre_madre": "CR Siria",
    "cod_madre": "985-5",
    "abuelo_paterno": "JDH Mr Amos Manso 568-6",
    "abuelo_materno ": "JDH Woodson De Manso 206-7",
    "criador": "Ganaderia Colono Real S.A",
    "ultimo_propietario": "Ganaderia Colono Real S.A"
   },
   {
    "id": "01-70292",
    "nombre": "CR Toronto",
    "hato": "893-3",
    "raza": "Brahman Gris Puro",
    "fecha_nacimiento": "02/11/2023",
    "nombre_padre": "JDH Woodson de Manso",
    "cod_padre": "206-7",
    "nombre_madre": "CR Africa ",
    "cod_madre": "858-4",
    "abuelo_paterno": "JDH MR Woodman Manso 578/6",
    "abuelo_materno ": "JDH Karu Manso 800",
    "criador": "Ganaderia Colono Real S.A",
    "ultimo_propietario": "Ganaderia Colono Real S.A"
   },
   {
    "id": "01-70293",
    "nombre": "CR Cedro",
    "hato": "894-3",
    "raza": "Brahman Gris Puro",
    "fecha_nacimiento": "02/12/2023",
    "nombre_padre": "CR Espavel",
    "cod_padre": "275-7",
    "nombre_madre": "CR Soltera",
    "cod_madre": "319-1",
    "abuelo_paterno": "MR H Maddox Manso 684",
    "abuelo_materno ": "RS. Emperador del Guachipelin 558/2",
    "criador": "Ganaderia Colono Real S.A",
    "ultimo_propietario": "Ganaderia Colono Real S.A"
   },
   {
    "id": "01-70294",
    "nombre": "CR Guayacan",
    "hato": "895-3",
    "raza": "Brahman Gris Puro",
    "fecha_nacimiento": "02/12/2023",
    "nombre_padre": "JDH Wellington Manso",
    "cod_padre": "527-1",
    "nombre_madre": "CR Woodson",
    "cod_madre": "229-0",
    "abuelo_paterno": "JDH MR Echo Manso 237/1",
    "abuelo_materno ": "JDH Woodson de Manso 206/7",
    "criador": "Ganaderia Colono Real S.A",
    "ultimo_propietario": "Ganaderia Colono Real S.A"
   },
   {
    "id": "01-70298",
    "nombre": "CR Tornado",
    "hato": "899-3",
    "raza": "Brahman Gris Puro",
    "fecha_nacimiento": "02/16/2023",
    "nombre_padre": "JDH Woodson de Manso",
    "cod_padre": "206-7",
    "nombre_madre": "CR Africa",
    "cod_madre": "858-4",
    "abuelo_paterno": "JDH MR Woodman Manso 578/6",
    "abuelo_materno ": "JDH Karu Manso 800",
    "criador": "Ganaderia Colono Real S.A",
    "ultimo_propietario": "Ganaderia Colono Real S.A"
   },
   {
    "id": "01-70306",
    "nombre": "CR Chimbonazo",
    "hato": "907-3",
    "raza": "Brahman Gris Puro",
    "fecha_nacimiento": "02/22/2023",
    "nombre_padre": "JDH Beckton de Manso",
    "cod_padre": "490-7",
    "nombre_madre": "CR Emperatriz",
    "cod_madre": "161-9",
    "abuelo_paterno": "JDH MR Amos Manso 568/6",
    "abuelo_materno ": "RS. Emperador del Guachipelin 558/2",
    "criador": "Ganaderia Colono Real S.A",
    "ultimo_propietario": "Ganaderia Colono Real S.A"
   },
   {
    "id": "01-70377",
    "nombre": "CR Beckton",
    "hato": "910-3",
    "raza": "Brahman Gris Puro",
    "fecha_nacimiento": "03/01/2023",
    "nombre_padre": "JDH Beckton de Manso",
    "cod_padre": "490-7",
    "nombre_madre": "CR Emperatriz",
    "cod_madre": "161-9",
    "abuelo_paterno": "JDH MR Amos Manso 568/6",
    "abuelo_materno ": "RS. Emperador del Guachipelin 558/2",
    "criador": "Ganaderia Colono Real S.A",
    "ultimo_propietario": "Ganaderia Colono Real S.A"
   },
   {
    "id": "01-70379",
    "nombre": "CR Vesubio",
    "hato": "912-3",
    "raza": "Brahman Gris Puro",
    "fecha_nacimiento": "03/07/2023",
    "nombre_padre": "JDH Beckton de Manso",
    "cod_padre": "490-7",
    "nombre_madre": "CR Londrina",
    "cod_madre": "330-8",
    "abuelo_paterno": "JDH MR Amos Manso 568/6",
    "abuelo_materno ": "JDH Clanton De Manso 313-8",
    "criador": "Ganaderia Colono Real S.A",
    "ultimo_propietario": "Ganaderia Colono Real S.A"
   },
   {
    "id": "01-67344",
    "nombre": "CR Elijah",
    "hato": "820-2",
    "raza": "Brahman Gris Puro",
    "fecha_nacimiento": "08/02/2022",
    "nombre_padre": "MR H Elihah Manso",
    "cod_padre": "281-2",
    "nombre_madre": "CR Africa",
    "cod_madre": "858-4",
    "abuelo_paterno": "MR H Maddox Manso 684",
    "abuelo_materno ": "JDH Karu Manso 800",
    "criador": "Ganaderia Colono Real S.A",
    "ultimo_propietario": "Ganaderia Colono Real S.A"
   },
   {
    "id": "01-62360",
    "nombre": "CR Madero Negro",
    "hato": "661-0",
    "raza": "Brahman Gris Puro",
    "fecha_nacimiento": "03/03/2020",
    "nombre_padre": "MR H Maddox Manso",
    "cod_padre": "684",
    "nombre_madre": "CR Pondur",
    "cod_madre": "284-0",
    "abuelo_paterno": "JDH MR Manso 360-1",
    "abuelo_materno ": "MR AH REX Ponderosa 009",
    "criador": "Ganaderia Colono Real S.A",
    "ultimo_propietario": "Ganaderia Colono Real S.A"
   }
  ]
  }