name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main  # Cambia esto si tu rama principal tiene otro nombre
  pull_request:
    types: [opened, synchronize, reopened, closed]

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build and Deploy
      uses: Azure/static-web-apps-deploy@v1
      with:
        azure_static_web_apps_api_token: ${{ secrets.c73a8e79ca62577cf2d184edae19a9127cda628088b76c558c709a87269cffe804-221bda80-3aee-44f4-99da-49b8fe40af6701023200c7281a10 }}
        app_location: "/"  # Cambia según la ubicación de tu aplicación
        output_location: "build"  # Cambia esto si el output es diferente
        app_build_command: "npm run build"  # Comando personalizado de compilación
